### ISSUE TITLE
Rocto on Linux?

### ISSUE THREAD

**Issue by seonghobae** [roctoproject/rocto-rpackage#6]
Hello, This is Seongho Bae, From Korea republic of.

I already build the package with the future::future() API, in the Linux environments via SSH protocol.
However, the Rocto seems could be run on the Windows OS, so I interest this point.

So I want to use Rocto on Linux, the cluster side. Is possible?

**Comment by vankesteren** [comment]
rocto 를 향한 관심 정말 감사드립니다! 애석하지만 저희가 현 상황으로는 소프트웨어에 관한 도움을 드리기가 어렵습니다. 이 실험적인 코드에 이제야 다시 눈길을 좀 주기 시작했거든요. 리포지터리에 계속 눈을 두시고 계시면 새로운 정보나 업데이트를 가장 빠르게 받아보실 수 있으실거에요.

(이 이슈는 제가 닫도록 하겠습니다.)
EJ

(PS: a friend translated this for me 😄 )
